"""人工核对的玩家说明；属性和贴图由 build.py 从源码读取。"""
CATEGORIES = {'guide':'流程攻略','boss':'首领图鉴','item':'道具图鉴','npc':'人物图鉴','enemy':'敌怪图鉴','place':'地区与建筑','mechanic':'机制百科'}
ENTRIES = []
def entry(id, title, category, summary, sections, related=(), source=(), image=None, stats=None, tag=None):
    ENTRIES.append(dict(id=id,title=title,category=category,summary=summary,sections=sections,related=list(related),source=list(source),image=image,stats=stats or {},tag=tag))
def item(id,title,path,summary,obtain,usage,related=(),recipe=None,stats=None,image=None,tag=None):
    sections={'获取方式':obtain,'使用与效果':usage}
    if recipe: sections['合成配方']=recipe
    entry(id,title,'item',summary,sections,related,['Content/Items/'+path],image,stats,tag)
WAVE='击败再不斩与白后，四种职业武器保底随机获得一把；另有 20% 概率额外获得一把不同的武器。专家模式通过宝藏袋领取同样的武器奖励。'
item('kubikiribocho','斩首大刀','Weapons/Kubikiribocho.cs','挥动沉重的近战巨刀，命中有机会恢复生命。',WAVE,'命中非无敌敌人时，20% 概率恢复 2 生命。可以自动连续挥动。',['wave-duo','zabuza','chakra'])
item('senbon','千本','Weapons/Senbon.cs','一次扇形投出三根千本，可反复使用。',WAVE,'每次投掷三根千本，不消耗物品。与写轮眼的看破效果有联动。',['wave-duo','haku','sharingan'])
item('water-dragon','水遁·水龙弹之术','Weapons/WaterDragonJutsu.cs','结印释放追向敌人的水龙，属于魔法武器。',WAVE,'消耗原版魔力，发射可追踪敌人的水龙。查克拉和魔力是不同的资源。',['wave-duo','chakra'])
item('ice-mirror','秘术·魔镜冰晶','Weapons/IceMirrorJutsu.cs','召唤冰镜，向敌人投出千本。',WAVE,'在鼠标位置召唤冰镜，每面占用一个召唤栏位。使用时消耗魔力。',['wave-duo','haku'])
item('kunai','训练苦无','TrainingKunai.cs','木叶下忍的基础远程忍具。','新角色获得的初始物品。','投掷后不消耗，可以连续使用。',['getting-started','sharingan'])
item('wraps','训练用绷带','Taijutsu/TaijutsuWeapon.cs','早期可制作的体术武器，每次出拳产生风压。','在工作台制作。','左键打出风压，右键施展木叶旋风。八门开启时，风压更大、射程更长。',['taijutsu','gates'],'任意木材 ×10 ＋ 丝绸 ×3 → 训练用绷带 ×1；工作台。',{'基础伤害':'14','使用时间':'15 帧','伤害类型':'体术','击退':'3'},'Content/Items/Taijutsu/TrainingWraps.png')
item('leg-weights','小李的负重护腿','Taijutsu/TaijutsuWeapon.cs','比训练绷带更强、更快的体术武器。','参与击败我爱罗的角色首次胜利必得；常规掉落规则另以 1/3 概率掉落。','左键风压、右键木叶旋风，右键冷却 1.5 秒。属于武器，不是装备后增加属性的饰品。',['gaara','taijutsu','gates'],stats={'基础伤害':'30','使用时间':'12 帧','伤害类型':'体术','击退':'4'},image='Content/Items/Taijutsu/LeeLegWeights.png')
item('sharingan','装在试管里的写轮眼（一勾玉）','StyleCores/TierOneCores.cs','写轮眼流派的第一阶核心，以饰品形式装备。','首次完成死亡森林大蛇丸遭遇获得，倒下时在复活后发放；用蛇蜕重战另有 25% 概率掉落。','木头自然恢复间隔由 20 秒缩短至 16 秒。V 键【看破】消耗 30 查克拉，冷却 20 秒，4 秒内受到第一次攻击时自动替身；成功后 3 秒伤害 +15%。苦无、千本命中被看破的敌人必定暴击。',['orochimaru','styles','substitution'],image='Content/Items/StyleCores/SharinganCore1.png')
item('gates','八门遁甲之卷','StyleCores/TierOneCores.cs','八门流派第一阶核心，可开启前三门。','参与击败我爱罗的角色首次胜利必得；常规掉落规则另以 25% 概率掉落。','体术攻速 +10%。每按 V 开一门，耗 20 查克拉；每门伤害、移动速度 +10%。一至三门每秒分别失去 2/4/6 生命。三门后再按关闭；生命低于 20% 强制关闭并进入 10 秒疲劳。',['gaara','styles','taijutsu'],image='Content/Items/StyleCores/EightGatesCore.png')
item('byakugan','白眼','StyleCores/TierOneCores.cs','白眼流派第一阶核心，提供点穴与回天。','宁次以 25% 概率掉落。','看见附近敌人，近战命中叠加点穴，每层防御 −4，最多三层；Boss 每层多受 5% 伤害。V 键【回天】消耗 40 查克拉，冷却 15 秒，持续 1 秒，抵消敌方弹幕并弹开近身敌人。',['neji','styles'],image='Content/Items/StyleCores/ByakuganCore.png')
item('pill','兵粮丸','ChakraPill.cs','应急补充查克拉的消耗品。','工作台制作；湖边水牢事件结束也会奖励 3 个。','立即恢复 40 查克拉，之后 10 秒不能再次服用。',['chakra','lake'],'蘑菇 ×1 ＋ 太阳花 ×1 → 兵粮丸 ×2；工作台。')
item('crystal','查克拉结晶','ChakraCrystal.cs','永久增加查克拉上限的消耗品。','地下探索获得；每个角色首次击败波之国双首领奖励一个。','每次使用增加 20 上限，初始 100，最多 200，共可使用 5 个。',['chakra','wave-duo'])
item('handbook','忍者手册','NinjaHandbook.cs','游戏内的任务与机制查询入口。','新角色初始获得；可找卡卡西补发，也可重新制作。','使用后打开手册，查询当前任务、忍术、查克拉与首领线索。',['kakashi','getting-started'],'木材 ×1 → 忍者手册 ×1；无需制作站。')
item('insignia','雾隐标记','MistInsignia.cs','制作再不斩挑战卷轴的材料。','鬼之兄弟每人必掉一个；听达兹纳坦白后补得一个。','集齐三枚后，配合木材制作挑战卷轴。',['demon-brothers','tazuna','wave-scroll'])
item('wave-scroll','再不斩的挑战卷轴','ZabuzaChallengeScroll.cs','在大桥附近召唤波之国双首领战，不消耗。','断桥雾中见过再不斩后，在工作台制作。','距离大桥不超过 70 格使用。先召唤再不斩，半血后白加入。场上有再不斩或白时无法再召唤。',['wave-duo','bridge'],'雾隐标记 ×3 ＋ 木材 ×10 → 挑战卷轴 ×1；工作台；需要完成断桥雾中的相遇。',image='Content/Items/MissionScroll.png')
item('recommendation','中忍考试推荐书','ExamAdmissionScroll.cs','波之国后进入中忍考试的凭证。','波之国尾声后由卡卡西交付；遗失可补发。','携带它到忍者学校，找伊比喜开始笔试。',['exam-guide','ibiki','kakashi'])
for id,title,file in [('heaven','天之卷','HeavenScroll'),('earth','地之卷','EarthScroll')]:
    item(id,title,file+'.cs','死亡森林第二试所需的两种卷轴之一。','通过笔试后找红豆领取随机一种；完成塔前雨隐三人组战斗获得缺少的一种。','两卷一起放在背包，进入中央塔完成第二试。游荡小队当前只掉材料，不提供另一卷。',['forest','anko','rain-genin','tower'])
item('sound-token','音忍的对战牌','ExamRematchItems.cs','在中央塔大厅重复挑战多斯，不消耗。','在铁砧制作。','考试进度达到预选赛后，在中央塔大厅使用。',['dosu','tower'],'任意铁锭（铁/铅）×5 ＋ 暗影鳞片 ×5 或组织样本 ×5 → 对战牌 ×1；铁砧。',image='Content/Items/ExamAdmissionScroll.png')
item('sand-gourd','砂隐的葫芦','ExamRematchItems.cs','在考试会场重复挑战我爱罗，不消耗。','在铁砧制作。','考试进度达到正式赛后，在会场场地使用。当前借用原版陶盆图标。',['gaara','stadium'],'沙块 ×50 ＋ 骨头 ×10 → 葫芦 ×1；铁砧。')
item('snake-skin','蛇的蜕皮','SnakeSkin.cs','将大蛇丸再次引出的召唤物，不消耗。','大蛇丸遭遇结束留下；也可在铁砧制作。','在丛林地表使用，直接召唤本体。当前借用原版皮革图标。',['orochimaru','forest'],'藤蔓 ×3 ＋ 丛林孢子 ×10 ＋ 毒刺 ×5 → 蛇蜕 ×1；铁砧。')
item('neji-scroll','宁次的切磋书','NejiChallengeScroll.cs','在考试会场与宁次切磋，不消耗。','正式赛阶段找卡卡西领取。','在会场中央使用；考试进度需达到正式赛；宁次或我爱罗在场时不能使用。',['neji','kakashi','stadium'],image='Content/Items/ExamAdmissionScroll.png')
item('medal','波之国功绩牌','WaveCountryMedal.cs','波之国双首领首胜饰品。','每个角色第一次击败再不斩与白获得。','装备后防御 +2。',['wave-duo'])
item('headband','中忍护额','ChuninHeadband.cs','完成中忍考试的奖励饰品。','参与击败我爱罗后取得。','防御 +3，近战与魔法伤害各 +4%。',['gaara','exam-guide'])
item('bag','宝藏袋（再不斩与白）','WaveBossBag.cs','专家及大师模式的波之国战斗奖励。','专家及大师模式下，双首领战结束后掉落。','右键打开。四种职业武器随机保底一把，20% 概率额外一把不同武器，两种头饰各有 1/7 概率，并获得 3 金币。奖杯在场外单独掉落，不在袋内。',['wave-duo','kubikiribocho','senbon','water-dragon','ice-mirror'])
for id,title,file in [('zabuza-head','再不斩护额','ZabuzaHeadband'),('haku-mask','白的面具','HakuMask')]:
    item(id,title,file+'.cs','波之国双首领战的头部时装。','双首领战结算时各自以 1/7 概率获得；专家模式从宝藏袋开出。','装在头部时装栏展示外观。',['wave-duo','bag'])
for id,title,file in [('zabuza-trophy','再不斩奖杯','ZabuzaTrophy'),('haku-trophy','白奖杯','HakuTrophy')]:
    item(id,title,file+'.cs','可放置的战斗纪念装饰。','双首领战结束时各自以 10% 概率掉落，所有难度均在战场掉落。','作为装饰放置，不包含在专家宝藏袋内。',['wave-duo'])
item('blueprint','达兹纳的施工图','BridgeBlueprint.cs','为没有大桥的世界补建大桥的工具。','没有大桥时找卡卡西领取。','海滩面朝大海使用，先显示轮廓，原地再次使用确认施工并消耗。每个世界只能一座；遇到自建方块拒绝施工。考试内容仍需要新世界的木叶与场地。',['bridge','kakashi'])

item('clone-scroll','分身术卷轴','Jutsu/SealScroll.cs','2 印忍术，召出两个分身优先代挡敌人的攻击。','角色初始化时自带在 2 印槽；已有存档会读取原有槽位配置。','装入 2 印槽，按 Z 后自动结印约 0.5 秒。消耗 15 查克拉，召出两个持续最多 8 秒的分身，每个可代挡一次敌人攻击或沙缚、杀气，优先于木头消耗。再次施展会替换旧分身。',['hand-seals','substitution','chakra'],stats={'印位':'2 印 · Z','查克拉消耗':'15','独立冷却':'无','伤害类型':'通用（无直接伤害）'},image='Content/Items/Jutsu/ScrollClone.png')
item('fireball-scroll','火遁·豪火球之术卷轴','Jutsu/SealScroll.cs','4 印忍术，释放穿墙的巨大火球并留下地面火焰。','当前已实现，可用开发调试指令 /m0 seals 获取；正常探索、任务与掉落来源尚未接入。','装入 4 印槽，按 X 后结印约 1 秒。消耗 40 查克拉，冷却 6 秒。火球朝鼠标方向前进，半秒内涨至直径约 13 格，最长持续 2 秒，可穿过方块并灼烧沿途敌人、留下持续约 3 秒的地火。命中 Boss 或生命上限不低于火球伤害五倍的大型敌人时立即爆炸；小敌人不会阻止其继续前进。爆炸基础伤害为火球的 1.5 倍。',['hand-seals','chakra','chidori-scroll'],stats={'印位':'4 印 · X','基础伤害':'32','查克拉消耗':'40','独立冷却':'6 秒','伤害类型':'通用'},image='Content/Items/Jutsu/ScrollFireball.png',tag='开发试用')
item('chidori-scroll','千鸟卷轴','Jutsu/SealScroll.cs','6 印忍术，蓄积雷电后向鼠标方向突进。','当前已实现，可用开发调试指令 /m0 seals 获取；卡卡西教学等正常获取流程尚未接入。','装入 6 印槽，按 C 后结印约 1.5 秒，再蓄雷约 1.5 秒。消耗 60 查克拉，冷却 10 秒。蓄雷时头顶显示充能条，移动减慢、无法使用物品，周围电光会伤害敌人；蓄雷阶段仍可受击。随后向鼠标方向最多冲出约 40 格，突进期间无敌；穿过小敌人，命中首个 Boss 后停止并造成 2.5 倍基础打击伤害。可穿过约三格厚的薄墙，厚墙会阻挡；路径留下持续约 3 秒的雷电。',['hand-seals','chakra','fireball-scroll'],stats={'印位':'6 印 · C','基础伤害':'120','查克拉消耗':'60','独立冷却':'10 秒','伤害类型':'通用'},image='Content/Items/Jutsu/ScrollChidori.png',tag='开发试用')

def article(id,title,cat,summary,sections,related,source,image=None,stats=None,tag=None):
    entry(id,title,cat,summary,sections,related,source,image,stats,tag)
article('wave-duo','波之国双首领战','boss','再不斩与白共同构成一场战斗；先倒下的人会改变另一人的招式。',{'召唤与地点':'完成达兹纳与湖边事件，在断桥雾中见过再不斩后制作挑战卷轴，在海边大桥 70 格内使用。','战斗阶段':['先与再不斩交战，半血时触发转场，白加入并展开冰镜牢笼。','先击败白：再不斩进入暴走，使用往返飞刀与口咬苦无突进，同时受到的伤害增加 25%。','先击败再不斩：白进入暴走，六面冰镜会重生，并使用千杀水翔。','两人均倒下才结算本场奖励并进入尾声。'],'奖励':'四种职业武器随机保底一件；20% 概率额外一件不同武器。两种头饰各 1/7，奖杯各 10%。专家模式武器和头饰由宝藏袋发放；每角色首胜获得查克拉结晶与功绩牌。','应对建议':'先看起手再移动，留意木头层数，并保留查克拉用于瞬身或结印。白的冰镜可击破；击杀顺序会改变后半场，按自己擅长处理的招式选择。此段为机制推导建议，尚未做独立攻略实测。'},['zabuza','haku','wave-scroll','wave-guide','bag','crystal'],['Common/WaveDuoRules.cs','Common/Systems/WaveRewards.cs','Common/WaveLootRules.cs'], 'Content/NPCs/Zabuza_Idle_0.png',tag='双首领')
article('zabuza','桃地再不斩','boss','波之国双首领战的先出场首领，使用巨刀、水遁与浓雾。',{'出场':'由再不斩的挑战卷轴召唤，战斗与白共用奖励结算。','招式与阶段':'巨刀挥砍、冲刺、瞬身与水遁。半血进入浓雾并让白加入；白先倒下后进入暴走。','暴走变化':'使用往返飞刀和口咬苦无突进，受到伤害增加 25%。'},['wave-duo','haku','kubikiribocho','wave-scroll'],['Content/NPCs/ZabuzaBoss.cs','Common/ZabuzaCombatRules.cs','Common/WaveDuoRules.cs'],'Content/NPCs/Zabuza_Idle_0.png',{'基础生命':'1800','基础防御':'7'})
article('haku','白','boss','借助魔镜冰晶移动，以千本与冰遁封锁大桥。',{'出场':'再不斩半血后加入双首领战，当前不使用独立白召唤物。','冰镜牢笼':'出场展开八面可破冰镜，边界会推回玩家。','暴走变化':'再不斩先倒下时使用六面会重生的冰镜与千杀水翔。'},['wave-duo','zabuza','senbon','ice-mirror'],['Content/NPCs/HakuBoss.cs','Common/WaveDuoRules.cs'],'Content/NPCs/Haku_Idle_0.png',{'基础生命':'900','基础防御':'4'})
article('dosu','音忍·多斯','boss','中央塔预选赛的对手，以音波和响鸣穿进攻。',{'如何挑战':'带齐天地卷进入中央塔，通过第二试后找月光疾风开始预选赛。重复挑战使用音忍的对战牌。','招式':'响鸣穿、音波冲击、地面震波、共鸣环、跃起下砸。半血后起手时间缩短，音波变为两次。','异常状态':'响鸣穿可引发耳鸣，短时间左右移动反向，持续不超过 2 秒。','胜利':'记为预选赛合格。击败骷髅王或生命上限达到 400 后可进入正式赛。'},['sound-token','hayate','tower','gaara','status'],['Content/NPCs/Dosu.cs','Common/ExamBossRules.cs','Common/Systems/ExamBoutSystem.cs'],'Content/NPCs/Dosu_Idle_0.png',{'基础生命':'2200','基础防御':'8'})
article('gaara','砂瀑之我爱罗','boss','中忍考试正式赛对手，经历沙之铠、铠甲破裂和局部尾兽化三阶段。',{'如何挑战':'预选赛合格，并击败骷髅王或生命上限达到 400 后，进入木叶城墙外考试会场。再战使用砂隐的葫芦。','阶段':['生命超过 50%：沙之铠阶段。','生命降至 50%：铠甲破裂，节奏加快、弹幕变密，并加入贴地沙浪。','生命降至 25%：局部尾兽化，砂之巨臂与风弹；不再使用砂墙。'],'砂墙与破绽':'前两阶段约每 8–10 秒升起砂墙；累计受到 260 正面伤害会提早触发。砂墙持续 3 秒，正面伤害降低 90%，背后可正常攻击；之后 2 秒喘息，可从各方向攻击。铠甲破裂不会打断正在进行的守护与喘息窗口。','弹幕与预警':['砂手里剑：扇形发射 5 枚，铠甲破裂后增至 7 枚。','流沙：在玩家脚下及两侧标出 3 处位置，铠甲破裂后增至 5 处。中央标记约 50 帧后喷出沙柱，两侧稍晚；相邻位置约隔 6 格，可利用空隙躲避。','砂弹：移动接近玩家时甩出砂弹，铠甲破裂后频率提高。','沙缚柩：先标记玩家脚下，再尝试束缚。束缚落下时，分身或木头可自动代挡；没有保护时会被裹住，F 键不再直接解除束缚。应在预警阶段移开，避免后续砂瀑送葬。'],'应对思路':'留意脚下的流沙标记，不要停在标记上持续输出。砂墙升起时绕至背后，或等守护结束后的喘息窗口再攻击；进入局部尾兽化后改为躲避巨臂与风弹。','奖励':'参与角色首胜获得八门核心与小李负重护腿，并取得中忍护额。常规掉落规则另包含八门 25%、护腿 1/3。','开发边界':'完全尾兽化、木叶崩溃与可收服守鹤属于后续规划，当前不作为可玩攻略。'},['gates','leg-weights','headband','sand-gourd','stadium','status','roadmap'],['Content/NPCs/Gaara.cs','Content/Projectiles/GaaraBullets.cs','Common/ExamBossRules.cs'],'Content/NPCs/Gaara_Idle_0.png',{'基础生命':'5200','基础防御':'14'})
article('neji','日向宁次','boss','正式赛阶段开放的可选切磋对手，柔拳会封住查克拉穴位。',{'如何挑战':'正式赛阶段找卡卡西领取切磋书，在考试会场使用。无需把切磋安排在我爱罗之后，但场上不能有我爱罗。','招式':'柔拳点穴、回天、八卦六十四掌。回天可反弹飞行道具，注意其起手和旋转时段。','点穴封印':'每层减少 20 查克拉上限，最多三层，满层暂时封住替身术；封印持续 10 秒。','掉落':'白眼核心，概率 25%。'},['byakugan','neji-scroll','status','stadium'],['Content/NPCs/Neji.cs','Common/ExamBossRules.cs'],'Content/NPCs/Neji_Idle_0.png',{'基础生命':'4000','基础防御':'12'},'可选切磋')
article('orochimaru','大蛇丸（死亡森林）','boss','死亡森林中段的必经遭遇，以草隐考生身份靠近玩家。',{'遭遇流程':'通过入口小队后，在森林中段遇到孤身的草隐考生。攻击他会触发蛇蜕与本体出场；靠近则触发揭面与杀气。两种出场方式都会释放杀气，生命降至 75% 后还会再次释放。','结束条件':'打至半血、撑满 90 秒或玩家倒下时结束。尚未击败世吞/克脑且生命上限不到 300 的玩家，只需撑 60 秒，伤害降为约七成。中途逃走不算完成。','近身招式':'潜影蛇手向前伸出三条蛇；蛇行突进沿地面绕至玩家身后；风遁击退后接蛇手；长颈咬追向出招时锁定的位置。五行封印近身命中后，暂停自然与命中查克拉恢复 8 秒，但兵粮丸仍可使用。','弹幕与预警':['蛇群：朝玩家扇形发射 5 条小蛇，巨蛇出场后增至 7 条。招式间隙还会投出小蛇，巨蛇出场后更密集。','毒液：向玩家附近抛出三团弧线毒液，落地留下持续约 5 秒的毒池，命中可造成中毒。','蛇雨：5 条蛇悬在玩家上方，闪烁并显示向下的紫色虚线，再依次落下；巨蛇出场后增至 7 条。相邻落点约隔 5.5 格。','草薙剑：先显示闪烁的瞄准线，约 34 帧后沿该方向伸出长剑。','通灵巨蛇：生命降至 75% 或战斗满 35 秒后，在招式间隙召唤一次。先有地面震动预警，再贴地冲过。'],'应对思路':'杀气先显示约 1 秒的红色扇形预警；离开范围或利用地形遮挡视线可躲避。仍在范围内时，分身或木头可代挡；两者耗尽则会短暂无法移动，F 键不再直接解控。蛇雨出现时观察虚线，移到落点之间；草薙剑出招前离开瞄准线。避开地面的毒池，查克拉被封时可用兵粮丸应急。遭遇可以靠撑过时间完成。','奖励与再战':'首次遭遇结束必给写轮眼试管，倒下则复活后补发。留下蛇蜕，可在丛林地表重复召唤本体，再战试管概率 25%。'},['sharingan','snake-skin','forest','status','substitution','pill'],['Content/NPCs/Orochimaru.cs','Content/NPCs/OrochimaruDisguise.cs','Content/Projectiles/OrochimaruBullets.cs','Content/Projectiles/GiantSnake.cs','Common/Systems/DeathForestSystem.cs','Common/Players/ChuninExamPlayer.cs','Common/ExamBossRules.cs'],'Content/NPCs/Orochimaru_Idle_0.png',{'基础生命':'5000','基础防御':'12'},'遭遇战')

for id,title,img,summary,where,role,related,source in [
('kakashi','旗木卡卡西','Kakashi','任务向导，也能陪玩家练习替身术。','木叶及波之国相关剧情地点。','补发忍者手册、引导任务、替身术练习；波之国后交付考试推荐书，正式赛阶段转交宁次切磋书。',['handbook','substitution','recommendation','neji-scroll'],'Kakashi.cs'),
('tazuna','达兹纳','Tazuna','波之国护送任务的委托人和大桥建造者。','海边与大桥附近。','初见交谈启动任务；击败鬼之兄弟后听他坦白，获得第三枚雾隐标记。',['wave-guide','insignia','bridge'],'TazunaBridge.cs'),
('ibiki','森乃伊比喜','Ibiki','主持中忍考试第一试。','木叶忍者学校。','带着推荐书找他开始笔试；第十题选择接受即可合格。',['written','recommendation','konoha'],'Ibiki.cs'),
('anko','御手洗红豆','Anko','死亡森林第二试的监考。','第四十四演习场入口监考小屋。','笔试合格后通过对话领取天之卷或地之卷。',['forest','heaven','earth'],'ExamProctors.cs'),
('hayate','月光疾风','Hayate','中央塔大厅的预选赛主考官。','死亡森林中央塔大厅。','通过第二试后，找他对话开始多斯战；失败后可以再找他。',['tower','dosu'],'ExamProctors.cs'),
('hiruzen','猿飞日斩','Hiruzen','介绍流派与立志的三代火影。','木叶火影办公室。','首次获得核心后可找他立志；改投需要 10 金币。',['styles','vow','konoha'],'Hiruzen.cs'),
('haku-forest','采药的少年','HakuForest','森林中的白，以非战斗身份与玩家相遇。','波之国相关森林区域。','提供剧情氛围与对话；与战斗中的白分开记录。',['haku','wave-guide'],'HakuForest.cs')]:
    article(id,title,'npc',summary,{'出现地点':where,'交互与作用':role},related,['Content/NPCs/'+source],'Content/NPCs/'+img+'.png')
article('demon-brothers','鬼之兄弟','enemy','波之国路上的双人伏击，以锁链与近身攻击阻拦护送。',{'出现':'波之国任务中首次伏击。','掉落':'每人必掉一枚雾隐标记；之后找达兹纳坦白，补齐制作挑战卷轴所需三枚。'},['wave-guide','insignia','tazuna'],['Content/NPCs/DemonBrother.cs','Common/Systems/DemonBrotherAmbushSystem.cs'],'Content/NPCs/DemonBrotherGozu.png')
article('candidates','死亡森林考生小队','enemy','以三人为一队行动的考试敌人。',{'固定与游荡':'入口有固定埋伏小队，整队倒下后推进遭遇进度；之后林中可出现游荡小队。','掉落与卷轴':'当前游荡小队只提供材料，不按旧版 25%／第五队保底发另一卷。另一卷由塔前雨隐战提供。','战斗':'使用苦无、手里剑与烟雾弹。'},['forest','rain-genin'],['Content/NPCs/ForestExamCandidate.cs','Common/Systems/DeathForestSystem.cs'],'Content/NPCs/ForestCanopyCandidate.png')
article('rain-genin','雨隐三人组','enemy','中央塔前的固定伏击，持有玩家缺少的一卷。',{'触发':'死亡森林大蛇丸遭遇完成后，在塔前空地触发；已有两卷时不再伏击。','战斗与奖励':'使用千本雨与分身。整队击败后获得缺少的卷轴。'},['forest','heaven','earth','orochimaru'],['Content/NPCs/ForestExamCandidate.cs','Common/Players/ChuninExamPlayer.cs','Common/Systems/DeathForestSystem.cs'],'Content/NPCs/RainGenin.png')

article('getting-started','新手入门','guide','从新世界的木叶村出发，开始你的忍者冒险。',{'准备':['使用 Terraria 1.4.4 对应的 tModLoader，安装并启用 Terruto。','新建世界：木叶、大桥和考试场地在世界生成时建立。旧世界不自动补齐考试场地。','新角色带有训练苦无与忍者手册，先阅读手册并找卡卡西。'],'基本操作':'敌人命中时有木头会自动替身。F：消耗两根木头与 15 查克拉，瞬身并潜伏 5 秒；V：流派核心奥义。Z/X/C 分别发动 2/4/6 印槽的忍术，按一下后自动结印。按键可在游戏设置中修改；体术武器右键可冲刺踢。','从哪里开始':'跟着卡卡西的线索去海边见达兹纳。火影内容与原版探索并行，保留全部原版 Boss。','当前范围':'目前可玩内容到中忍考试。单人体验为主要验证方向，联机尚未完整验收；考试及近期战斗仍在调整。'},['wave-guide','progression','kunai','handbook','substitution'],['Common/Players/StoryPlayer.cs','Common/Systems/ShinobiKeybinds.cs','Common/ChuninExamRules.cs'])
article('wave-guide','波之国流程','guide','从护送达兹纳到大桥双首领战的完整路线。',{'任务步骤':['海边与达兹纳交谈，接受护送任务。','遭遇鬼之兄弟，收集两枚雾隐标记，再听达兹纳坦白获得第三枚。','地表湖边初遇再不斩，打破水牢救出卡卡西。','前往海边断桥，完成雾中与再不斩的相遇，解锁挑战卷轴配方。','工作台制作再不斩挑战卷轴，在大桥附近使用，击败再不斩与白。','看完尾声，卡卡西交付推荐书，回木叶参加中忍考试。'],'准备建议':'留意木头层数，熟悉 F 瞬身与 Z 分身术，探索生命水晶并准备原版装备。需要方向时查看忍者手册或找卡卡西。'},['tazuna','demon-brothers','lake','wave-scroll','wave-duo','exam-guide'],['Common/StoryRules.cs','Common/Players/StoryPlayer.cs','Common/Systems/LakeAmbushSystem.cs','Common/Systems/WaveEpilogueSystem.cs'])
article('lake','湖边水牢事件','guide','初遇再不斩，解救被水牢困住的卡卡西。',{'触发':'完成达兹纳相关前置后，在地表湖边进入剧情。','目标与奖励':'攻击并打破水牢。事件结束奖励 50 银币与 3 个兵粮丸，之后推进大桥剧情。'},['wave-guide','kakashi','pill'],['Common/Systems/LakeAmbushSystem.cs','Content/NPCs/WaterPrison.cs'])
article('exam-guide','中忍考试流程','guide','笔试、死亡森林、预选赛与正式赛组成当前第二篇章。',{'完整步骤':['波之国结束后，找卡卡西取得推荐书。','忍者学校找伊比喜开始笔试，第十题选择接受。','丛林入口找红豆领卷；击败入口小队。','森林中段完成大蛇丸遭遇；塔前击败雨隐三人组，补齐两卷。','带齐天地卷进入中央塔，再找疾风对话开始多斯战。','预选合格后，击败骷髅王或把生命上限提升到 400。','进入木叶城墙外会场与我爱罗交战；正式赛阶段还可用切磋书挑战宁次。'],'进度记录':'考试进度主要按角色存档；首领击败标记按世界记录。请使用带有木叶和考试地标的新世界。'},['written','forest','tower','dosu','gaara','neji','progression'],['Common/ChuninExamRules.cs','Common/Players/ChuninExamPlayer.cs','Common/Systems/ExamBoutSystem.cs','Common/Systems/DeathForestSystem.cs'])
article('written','第一试·笔试','guide','伊比喜主持的九道随机题与第十题。',{'开始':'带着考试推荐书，在忍者学校找伊比喜开始。','合格规则':'九题从题库随机抽取，答错不直接淘汰；第十题选择接受即合格。选择放弃则需要等下一次天亮重考。','奖励':'合格时按前九题正确数发钱，每题 10 银币，最多 90 银币。奖励在合格时结算。'},['ibiki','recommendation','exam-guide','forest'],['Common/WrittenExamBank.cs','Common/ChuninExamRules.cs','Common/Systems/WrittenExamSystem.cs'])
article('konoha','木叶隐村','place','出生点附近生成的城镇，是任务之间的落脚处。',{'建筑与人物':'包含忍者学校、火影办公室、村庄住宅等；卡卡西、伊比喜与三代承担任务引导。','世界生成':'需要新世界。木叶的住房与地区背景随模组生成；原版 NPC 可在这里居住。'},['kakashi','ibiki','hiruzen','stadium'],['Common/KonohaDesign.cs','Common/Systems/KonohaWorld.cs','Common/Systems/KonohaBiome.cs'])
article('bridge','波之国大桥','place','海边浓雾中的双首领战场。',{'用途':'承载达兹纳任务、雾中相遇、双首领战与尾声。','召唤范围':'再不斩挑战卷轴需要在大桥 70 格内使用。','没有大桥':'可找卡卡西获取施工图，在海滩面朝大海确认补建；这不会补齐中忍考试地标。'},['wave-duo','wave-scroll','tazuna','blueprint'],['Common/Systems/WaveBridgeWorld.cs','Content/Items/ZabuzaChallengeScroll.cs'])
article('forest','死亡森林','place','原版丛林中的第二试区域，连接第四十四演习场入口与中央塔。',{'当前路线':'红豆领卷 → 入口小队 → 中段大蛇丸 → 塔前雨隐 → 带齐两卷进入中央塔。','地标':'入口大门、监考小屋、铁丝网、空心巨树、警告牌与中央塔。森林在另一方向时布局镜像。','注意':'第二试不限时。游荡考生不会提供另一卷；先完成固定遭遇路线。'},['anko','orochimaru','rain-genin','tower','exam-guide'],['Common/Systems/DeathForestSystem.cs','Common/ExamSiteDesign.cs','Common/Systems/ExamSiteWorld.cs'])
article('tower','中央塔','place','第二试终点与预选赛场。',{'第二试':'背包携带天之卷和地之卷，进入中央塔完成第二试。','预选赛':'大厅找疾风对话开启多斯战，重复挑战可用对战牌。'},['hayate','dosu','sound-token','heaven','earth'],['Common/ExamSiteDesign.cs','Common/Systems/ExamSiteWorld.cs','Content/NPCs/ExamProctors.cs'])
article('stadium','中忍考试会场','place','木叶城墙外的正式赛场地。',{'正式赛':'通过预选并达到骷髅王或 400 生命门槛后，进入场地触发我爱罗战。','切磋与再战':'宁次切磋书和砂隐葫芦都需要在会场场地内使用。'},['gaara','neji','sand-gourd','neji-scroll'],['Common/ExamSiteDesign.cs','Common/Systems/ExamBoutSystem.cs'])
article('chakra','查克拉','mechanic','所有职业共用的独立资源，供替身术与流派奥义使用。',{'上限':'初始 100；每颗结晶 +20，当前最多 200。与魔力条相互独立，普通魔法忍术仍用魔力。','恢复':'平稳状态每秒 10；恢复延迟期间每秒 3。命中额外回复 2，每秒总预算 5，防止高频攻击无限回满。兵粮丸立即恢复 40。','异常影响':'五行封印暂停自然与命中恢复；宁次的点穴降低可用上限，三层封住替身术。'},['crystal','pill','substitution','styles','status'],['Common/ChakraRules.cs','Common/Players/ChakraPlayer.cs'])
article('substitution','替身术与木头','mechanic','木头自动替你挡伤，F 键主动瞬身进入潜伏。',{'木头与自动替身':'初始最多两根木头。敌人或敌方弹幕命中时，自动消耗一根挡下这一击，并移至附近安全位置，获得约 1 秒无敌；无需提前按键。分身存在时优先由分身代挡。环境伤害不属于木头的自动保护范围。','恢复':'缺少木头时，每 20 秒恢复一根；命中敌人可推进约 0.1 秒恢复进度。同一帧多次命中不叠加。装备一勾玉写轮眼后，自然恢复间隔缩短至 16 秒。复活时补满木头。','主动瞬身':'默认 F；消耗两根木头和 15 查克拉，朝移动方向或面朝方向瞬身，获得约 0.5 秒无敌与 5 秒潜伏。按键有 0.5 秒防重复触发间隔；会取消正在进行的结印。自动挡伤本身不提供潜伏。','控制与限制':'沙缚柩和杀气落下时可由分身或木头代挡；保护耗尽而被控制后，F 不再直接解控。宁次点穴满三层会封住自动替身与主动瞬身。','练习':'卡卡西的练习保留受击前按 F 的判定：按下后约 0.4 秒内接住苦无，不消耗查克拉或木头。该练习与实战的自动挡伤不同。'},['chakra','stealth','clone-scroll','sharingan','kakashi','status'],['Common/ChakraRules.cs','Common/StyleCoreRules.cs','Common/Players/SubstitutionPlayer.cs','Common/Players/SubstitutionDrillPlayer.cs','Content/Projectiles/SealJutsu.cs'])
article('styles','流派核心','mechanic','在原版职业之外，装备饰品选择一条修行路线。',{'当前可取得':'一勾玉写轮眼、八门第一阶、白眼第一阶。核心可替换，当前一次装备一个。','奥义':'默认 V，使用装备核心提供的主动技能，消耗查克拉。','职业搭配':'保留近战、远程、魔法、召唤职业；流派与职业分开，任何职业都能选择核心。','开发边界':'仙术核心、二三勾玉、后续形态与第二核心槽尚未作为当前可获取内容。'},['sharingan','gates','byakugan','vow','roadmap'],['Common/StyleCoreRules.cs','Content/Items/StyleCores/TierOneCores.cs','Common/Players/StyleCorePlayer.cs'])
article('taijutsu','体术武器','mechanic','以风压与木叶旋风为核心的武器类型。',{'用法':'左键打出风压；右键冲刺踢，约 1.5 秒冷却，冲刺期间短暂无敌。','成长':'训练用绷带可以合成，小李负重护腿来自我爱罗。八门会扩大风压并延长飞行距离。'},['wraps','leg-weights','gates'],['Content/Items/Taijutsu/TaijutsuWeapon.cs','Common/DamageClasses/TaijutsuDamage.cs'])
article('vow','立志','mechanic','获得流派核心后，与三代谈自己的忍道。',{'入口':'第一次获得核心后会收到三代想见你的提示，到火影办公室交谈。','改投':'首次立志后仍可改投，费用 10 金币。核心本身可以换装；立志与饰品装备分开记录。'},['hiruzen','styles'],['Common/VowRules.cs','Content/NPCs/Hiruzen.cs'])
article('status','战斗异常状态','mechanic','考试首领使用的控制与查克拉限制。',{'耳鸣':'多斯响鸣穿附带，短时间左右方向反转，最多 2 秒。','沙缚与杀气':'我爱罗沙缚柩有脚下预警，大蛇丸杀气有约 1 秒红色扇形预警；可提前走出范围，杀气还可用地形遮挡视线。效果落下时优先由分身或木头代挡；没有保护就会被控制，F 键不再直接解除。','点穴封印':'宁次每层减少 20 查克拉上限，最多三层，满层禁止自动替身、主动瞬身与开始结印；持续 10 秒。玩家白眼对敌人的点穴是另一种效果。','五行封印':'约 8 秒暂停自然与命中查克拉恢复；可服用兵粮丸。'},['dosu','gaara','neji','orochimaru','substitution','clone-scroll','hand-seals','pill'],['Common/Players/JutsuStatusPlayer.cs','Common/Players/SubstitutionPlayer.cs','Common/Players/SealPlayer.cs','Content/NPCs/Gaara.cs','Content/NPCs/Orochimaru.cs','Common/ExamBossRules.cs'])
article('progression','Boss 顺序与推进路线','guide','按剧情推进查看当前可挑战的首领与解锁。',{'主线':['波之国：达兹纳 → 鬼之兄弟 → 湖边水牢 → 再不斩与白。','中忍考试：笔试 → 入口小队 → 大蛇丸遭遇 → 雨隐三人组 → 多斯。','正式赛：预选合格 ＋ 骷髅王已击败或生命上限 ≥400 → 我爱罗。'],'可选分支':'宁次在正式赛阶段开放，掉落白眼，不是主线必打。','原版关系':'保留全部原版 Boss。路线中标注的原版节点是装备阶段参考；正式赛门槛是骷髅王或 400 生命二选一。大蛇丸的 300 生命／邪恶 Boss 条件影响难度与坚持时间，不再阻止第一次遭遇。'},['wave-duo','orochimaru','dosu','gaara','neji','exam-guide'],['Common/ChuninExamRules.cs','Common/Systems/DeathForestSystem.cs','Common/ExamBossRules.cs'])
article('roadmap','后续开发路线','guide','现有百科之外的设计方向，尚不作为当前游戏内容。',{'规划内容':'木叶崩溃、仙术路线、后续瞳术升级、尾兽与通灵兽支线，以及之后的火影主线。','使用说明':'这些是设计方向，获取方式与数值尚不作为攻略承诺。当前玩家百科以波之国和中忍考试实际实现为范围。'},['styles','gaara','getting-started'],['../specs/总纲_主线与支线结构.spec.md'],tag='规划中')

article('stealth','潜伏与潜伏攻击','mechanic','主动瞬身后短暂隐去身形，让下一击获得强化。',{'进入潜伏':'实战按 F，消耗两根木头和 15 查克拉后进入 5 秒潜伏；以增益图标显示。木头自动挡伤不会进入潜伏。','下一击':'潜伏中的下一次有效武器命中必定暴击，并额外提高 30% 最终伤害；命中后消耗潜伏，目标附近出现烟雾效果。仆从、哨兵及其弹幕不消耗也不获得该强化。','当前边界':'当前所有适用武器共用这一效果。忍具攒潜伏值、专属潜伏招式和后续盔甲加成仍是规划，未作为当前攻略。'},['substitution','chakra','kunai','hand-seals'],['Common/ChakraRules.cs','Common/Players/StealthPlayer.cs','Common/Players/SubstitutionPlayer.cs','Content/Buffs/StealthBuff.cs'],'Content/Buffs/StealthBuff.png')
article('hand-seals','结印与忍术卷轴','mechanic','Z、X、C 对应三个印位，按一下后自动结印施术。',{'装配与操作':['打开背包，把卷轴放入弹药栏旁的独立卷轴面板；2、4、6 印槽只能放对应印数的卷轴，并随角色存档保存。','默认 Z 发动 2 印槽，X 发动 4 印槽，C 发动 6 印槽。按一下即可自动结印，无需长按或松手。','每个印约需 0.25 秒：三槽结印分别约需 0.5、1、1.5 秒。头顶显示当前印序；完成后扣除查克拉并施术。'],'结印期间':'移动速度约为平时的 40%，不能使用物品。实际受伤会打断结印；分身或木头代挡的攻击不会打断。F 主动瞬身会取消结印。宁次点穴满三层时不能开始结印。','伤害与资源':'结印忍术使用独立查克拉，伤害按通用伤害和忍术强度计算，不使用单一职业的伤害加成。普通水龙弹等魔法武器仍耗魔力。','冷却提示':'HUD 木头图标下方显示三槽忍术与按键，冷却时变暗并显示剩余秒数，恢复可用时闪光。千鸟蓄雷另有头顶充能条。','已实现卷轴':'分身术开局装入 2 印槽。豪火球与千鸟已经可开发试用，可用 /m0 seals 获取；其正常任务、探索或掉落来源尚未接入，不能按规划文档当作当前获取路线。'},['clone-scroll','fireball-scroll','chidori-scroll','substitution','stealth','chakra'],['Common/SealRules.cs','Common/Players/SealPlayer.cs','Common/Systems/SealSlotsUI.cs','Common/Systems/SealOverlay.cs','Common/Systems/ChakraHud.cs','Common/Systems/ShinobiKeybinds.cs','Content/Items/Jutsu/SealScroll.cs','Content/Projectiles/SealJutsu.cs','Content/Commands/M0Command.cs'],image='Content/Items/Jutsu/ScrollFireball.png')

for e in ENTRIES:
    if e['id'] in ('clone-scroll','fireball-scroll','chidori-scroll'):
        e['source'] += ['Common/SealRules.cs','Common/Players/SealPlayer.cs','Content/Projectiles/SealJutsu.cs','Content/Commands/M0Command.cs']
