#!/usr/bin/env python3
"""Bake close-layer placement before play; regenerate after changing background art."""
import hashlib
import math
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "ShinobiPrototype/Common/BackgroundLayoutData.cs"
COVERAGE = 0.98


def main():
    lines = [
        "// Generated by scripts/export_background_layout.py; do not edit by hand.",
        "namespace ShinobiPrototype.Common;",
        "",
        "// Small records replace GPU readbacks and large temporary arrays on first region entry.",
        "public static class BackgroundLayoutData",
        "{",
        f"    public const float Coverage = {COVERAGE}f;",
        "    public readonly record struct Layer(int Width, int Height, int GroundRow, string Sha256);",
        "",
        "    public static Layer Close(string region) => region switch",
        "    {",
    ]
    for path in sorted((ROOT / "ShinobiPrototype/Backgrounds").glob("*Close.png")):
        with Image.open(path) as image:
            width, height = image.size
            alpha = image.convert("RGBA").getchannel("A").tobytes()
        needed = math.ceil(width * COVERAGE)
        row = next((y for y in range(height)
                    if sum(a > 128 for a in alpha[y * width:(y + 1) * width]) >= needed), -1)
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        region = path.stem.removesuffix("Close")
        lines.append(f'        "{region}" => new({width}, {height}, {row}, "{digest}"),')
    lines.extend(['        _ => new(0, 0, -1, ""),', "    };", "}", ""])
    OUTPUT.write_text("\n".join(lines))
    print(f"Exported close-layer placement: {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
