// Generated by scripts/export_background_layout.py; do not edit by hand.
namespace ShinobiPrototype.Common;

// Small records replace GPU readbacks and large temporary arrays on first region entry.
public static class BackgroundLayoutData
{
    public const float Coverage = 0.98f;
    public readonly record struct Layer(int Width, int Height, int GroundRow, string Sha256);

    public static Layer Close(string region) => region switch
    {
        "Konoha" => new(1024, 533, 400, "49e3d602c769f1020165cf0fd84958334eef10a99ba7b1f0b3f95bb16631ceea"),
        "Kusa" => new(1024, 533, 420, "6212586585c242f908277c2b32ceab8c939aa634e230450fbb1747b915f9b2be"),
        "Mist" => new(1024, 533, 490, "12e873d47ed1ad5891f41bc23b9a9dca50ccd8ad3250426fc986b9d1910fee34"),
        "Myoboku" => new(1024, 533, 443, "b6ec86aa23e47dfe764f07c9c76e0b9ff46ac17dfd8f0aed58148b42a406ca93"),
        "Snow" => new(1024, 533, 430, "74ab41b77e65c5e23cec8a73b03e22ba98d5c946b30da98fa610e0e96aab01dd"),
        "Suna" => new(1024, 533, 461, "05cdbd76893f581780ba6fc01591f3183a52782f019f0a466bcafa79f89807b2"),
        _ => new(0, 0, -1, ""),
    };
}
